#!/bin/sh

# Get the full query
q="$(echo | dmenu)"
[ -z "$q" ] && exit 0

# Extract the engine code
e="${q%% *}"

# Encode the search string
s=$(printf %s "${q#* }" | tr -d '\n' | od -t x1 -An | tr ' ' '%')

# Shortcuts:
# 'd' = duckduckgo.com
# 'w' = wikipedia.org
# 'a' = wiki.archlinux.org
# 'D' = en.wiktionary.org
case $e in
	'd')
		xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://duckduckgo.com/?q=${s}"
		;;
	'w')
		xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://en.wikipedia.org/wiki/index.php/Special:Search?search=${s}&go=Go"
		;;
	'a')
		xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://wiki.archlinux.org/index.php/Special:Search?search=${s}&go=Go"
		;;
	'D')
		xprop -id $1 -f _SURF_GO 8s -set _SURF_GO "https://en.wiktionary.org/w/index.php?search=${s}&go=Go"
		;;
	*)
		exit 1
		;;
esac
